// Authentication
export const AUTHENTICATION_RESET_PASSWORD_PARAMS = 'authentication/RESET_PASSWORD_PARAMS';
export const AUTHENTICATION_FORGET_PASSWORD_PARAMS = 'authentication/FORGET_PASSWORD_PARAMS';
export const AUTHENTICATION_UID_TOKEN = 'authentication/UID_TOKEN'
export const AUTHENTICATION_REMOVE_TOKEN = 'authentication/REMOVE_TOKEN'
export const AUTHENTICATION_VERIFY_OTP = 'authentication/VERIFY_OTP'
export const AUTHENTICATION_GET_RESEND_OTP = 'authentication/GET_RESEND_OTP'
export const AUTHENTICATION_FORGOT_PASSWORD = 'authentication/FORGOT_PASSWORD'
export const AUTHENTICATION_RESET_PASSWORD = 'authentication/RESET_PASSWORD'
export const LOGIN_SOCIAL_GOOGLE_REQUEST = 'authentication/LOGIN_SOCIAL_GOOGLE_REQUEST'
export const REGISTER_REQUEST = 'authentication/REGISTER_REQUEST'
export const REGISTER_CONFIRM_VERIFICATION = 'authentication/REGISTER_CONFIRM_VERIFICATION'
export const AUTHENTICATION_CHECK_EXISTING_PHONE_NUMBER_REQUEST = 'authentication/CHECK_EXISTING_PHONE_NUMBER_REQUEST'
export const AUTHENTICATION_STATUS = 'authentication/STATUS'
export const LOGIN_REQUEST = 'login/LOGIN_REQUEST';
export const SIGNUP_REQUEST = 'signup/SIGNUP_REQUEST';
export const LOGOUT_REQUEST = 'logout/LOGOUT_REQUEST';
